package model;

public enum BenefitType {
    HEALTH_INSURANCE,
    DENTAL_INSURANCE,
    LIFE_INSURANCE,
    MEAL_TICKETS,
    GYM_MEMBERSHIP,
    PUBLIC_TRANSPORT_PASS,
    COMPANY_CAR,
    PARKING_SPOT,
    TRAINING_BUDGET,
    EXTRA_VACATION_DAYS,
    CHILDCARE_SUPPORT,
    STOCK_OPTIONS,
    PERFORMANCE_BONUS,
    WELLNESS_PROGRAM,
    FREE_MEALS,
    HOUSING_ALLOWANCE,
    INTERNET_SUBSCRIPTION,
    PHONE_SUBSCRIPTION,
    EXTRA_VACATION
}
